### ISSUE TITLE
Gulp crushed after Node.js update to the latest version 12.10.0 (includes npm 6.10.3)

### ISSUE THREAD

**Issue by LilyMart7** [RivneITStep/teamlab#3]
I've updated  Node  to the latest version '12.10.0' today.  When I tried to run Gulp in my project folder I've got the following error (before everything worked flawlessly):

**Error message:**

fs.js:27
const { Math, Object } = primordials;
                         ^

ReferenceError: primordials is not defined
    at fs.js:27:26
    at req_ (C:\Users\Lily Mart\OneDrive\Desktop\TeamLab\start-template\node_modules\natives\index.js:143:24)
    at Object.req [as require] (C:\Users\Lily Mart\OneDrive\Desktop\TeamLab\start-template\node_modules\natives\index.js:55:10)
    at Object.<anonymous> (C:\Users\Lily Mart\OneDrive\Desktop\TeamLab\start-template\node_modules\vinyl-fs\node_modules\graceful-fs\fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)

**Comment by pancheliuga** [comment]
I suspect you're using node 12 and gulp 3. That combination does not work: https://github.com/gulpjs/gulp/issues/2324

A previous workaround from Jan. does not work either: https://github.com/gulpjs/gulp/issues/2246

Solution: Either upgrade to gulp 4 or downgrade to an earlier node.

**Comment by RivneITStep** [comment]
Everything is good with the gulp.
Just reinstall Node.js  https://nodejs.org/dist/v10.16.3/node-v10.16.3-x64.msi

**Comment by LilyMart7** [comment]
Great, thanks.  Now everything is worikng.
